name: Lint Code Base

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      statuses: write # for github/super-linter/slim to mark status of each linter run
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v8.0.0
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: .*css/.*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          LOG_LEVEL: NOTICE
          SUPPRESS_POSSUM: true
          VALIDATE_CHECKOV: false
          VALIDATE_CSS: false
          VALIDATE_EDITORCONFIG: false
          VALIDATE_JSCPD: false
          VALIDATE_MARKDOWN: false
